version: '3.1'

services:
  mongo:
    image: mongo:jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - 127.0.0.1:27018:27017
  api:
    image: e-com_server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_DB_URL=mongodb://root:example@mongo/e_com?authMechanism=DEFAULT&authSource=admin
      - PORT=3001
      - SECRET=kawens8a90danesasdacvs8gth
      - STRIPE_SECRET_KEY=sk_test_51MhPjfBUQ6Oq9GtlnK1ksaPnlK2gGtXwS6RQGUWFogQMbLVKQllwO3kME0i4ZbBtruPXj5ao7kpxEkZ4x1SPUUpn00AcJ0lTm8
      - SESSION_SECRET=2b3fa89sdafn3n9a-03nfdgads
      - CLIENT_URL=http://localhost:8080
    ports:
      - 127.0.0.1:3001:3001
    depends_on:
      - mongo
  client:
    image: e-com_frontend:latest
    ports:
      - 127.0.0.1:8080:80
    environment:
      - VITE_API_URL=http://api
      - VITE_GOOGLE_API_KEY=AIzaSyB5IVacuIdG2eT-smhlv_VdQEZhmR-r9WE
      - VITE_STRIPE_PUBLIC_KEY=pk_test_51MhPjfBUQ6Oq9GtltqHsBziImzqDSOenRkaWI8aePQ1HsPMmaDT4FmQobJyPWg3ZktoP3S5Dukh0QtQvcfVYx1fl00R2BAqcze
      - VITE_CONVERTKIT_API_URL=https://api.convertkit.com/v3
      - VITE_CONVERTKIT_API_KEY=B1uOm9gqGzOY2mWAbjjpMg
      - VITE_CONVERTKIT_API_SECRET=nHoRHKi_eg1QdBGs--jqyIl2LvgMVNqg8sCuFbZ-BXo
    depends_on:
      - api
